### ISSUE TITLE
Linux的Appimage运行时缺少libfuse2运行时库

### ISSUE THREAD

**Issue by ZzzzzzS** [limymy/bitbot_frontend-release#1]
如题，在使用Appimage封装版本的前端时缺少libfuse2这个库，需要用户手动安装才能运行，能否将这个库打包，获得更好的开箱体验，谢谢。

**Comment by limymy** [comment]
您是否在使用`ubuntu>=22.04`，这是Appimage的已知问题，参考[此链接](https://askubuntu.com/questions/1403811/appimage-on-ubuntu-22-04)。
